COMMON: Silence maybe-uninitialized warning
Compiles may warn about a possibly uninitialized variable. This is a false
positive, the variable is initialized in the code path where it is used.
Zeroize the variable on the declaration to silence this warning.

usr/lib/common/mech_aes.c: In function 'aes_xts_cipher':
usr/lib/common/mech_aes.c:4320:13: error: 'iv_prev' may be used uninitialized in this function [-Werror=maybe-uninitialized]
             memcpy(iv, iv_prev, AES_BLOCK_SIZE);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Ingo Franzki <ifranzki@linux.ibm.com>